### ISSUE TITLE
Creación de formulario de Login y Registro

### ISSUE THREAD

**Issue by emiliohernandezdev** [UMGMascotasAntigua/MascotasFE#1]
Crear formulario de login y registro en el repositorio de @UMGMascotasAntigua/devsquad/MascotasFE

**Comment by emiliohernandezdev** [comment]
Únicamente diseño de interfaz (HTML, CSS y JS).
La lógica se hará después

**Comment by Ale20GT** [comment]
[Login.zip](https://github.com/UMGMascotasAntigua/MascotasFE/files/15384197/Login.zip)
[Registro.zip](https://github.com/UMGMascotasAntigua/MascotasFE/files/15384198/Registro.zip)
